import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";

const leagueSpartan = League_Spartan({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "TastyTally",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${leagueSpartan.className} antialiased`}>
				{children}
			</body>
		</html>
	);
}
